# Generated by Django 4.2.6 on 2023-10-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterbooks',
            name='url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
